export const WORKSCHD_SENSITIVE_KEYS = new Set([
  'JWT_SECRET',
  'JWT_ACCESS_SECRET',
  'JWT_REFRESH_SECRET',
  'GOOGLE_CLIENT_SECRET',
  'KAKAO_CLIENT_SECRET',
  'SMTP_PASS',
  'SMTP_USER',
  'SOLAPI_API_KEY',
  'SOLAPI_API_SECRET',
  'BOK_API_KEY',
  'DART_API_KEY',
  'KIS_API_KEY',
  'KIS_API_SECRET',
  'TELEGRAM_BOT_TOKEN',
  'GEMINI_API_KEY',
  'MFA_ENCRYPTION_KEY',
  'SLACK_WEBHOOK_URL',
  'CLAUDE_API_KEY',
]);

export const AIPR_SENSITIVE_KEYS = new Set([
  'JWT_SECRET',
  'GITHUB_APP_PRIVATE_KEY_BASE64',
  'GITHUB_APP_CLIENT_SECRET',
  'GITHUB_WEBHOOK_SECRET',
  'ANTHROPIC_API_KEY',
  'GITLAB_WEBHOOK_SECRET',
]);
